// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz1RM8xlXxtpqCj9qkmofWZ_661Uh_1oI',
    appId: '1:434798664349:android:9bdfe341456df83cf59274',
    messagingSenderId: '434798664349',
    projectId: 'learn-firebase-50768',
    databaseURL: 'https://learn-firebase-50768-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learn-firebase-50768.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZUGWWCgP0TvH3X8L2-x2ZZzBc5BfryHY',
    appId: '1:434798664349:ios:378b079662619692f59274',
    messagingSenderId: '434798664349',
    projectId: 'learn-firebase-50768',
    databaseURL: 'https://learn-firebase-50768-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learn-firebase-50768.appspot.com',
    androidClientId: '434798664349-1eo6bejqcj9di8731r2rdd47eelj0ev5.apps.googleusercontent.com',
    iosClientId: '434798664349-c19868obei99f2gmtmpgarj0r9rgl0kn.apps.googleusercontent.com',
    iosBundleId: 'com.example.instacloneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1RqFT3YNHf8ox38Ehdtbm3wnnnxUZvqA',
    appId: '1:434798664349:web:3235436fa4872d75f59274',
    messagingSenderId: '434798664349',
    projectId: 'learn-firebase-50768',
    authDomain: 'learn-firebase-50768.firebaseapp.com',
    databaseURL: 'https://learn-firebase-50768-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learn-firebase-50768.appspot.com',
    measurementId: 'G-50YYC9PHSQ',
  );
}
